import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {MatMenuModule, MatMenuTrigger} from '@angular/material/menu';
import { IonicModule } from '@ionic/angular';

import {
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonButtons,
  IonCardTitle,
  IonSearchbar,
  IonContent,
  IonHeader,
  IonTitle,
  IonAvatar,
  IonThumbnail,
  IonTabs,
  IonTabBar,
  IonTabButton,
  IonIcon,
  IonLabel,
  IonItem,
  IonList,
  IonPopover,
  IonToolbar,
  IonInput,
  IonText,
  IonBackButton,
  IonCol,
  IonRow,
  IonBadge,
  IonGrid,
  IonFooter,
  IonSegment, 
  IonSegmentButton,
  IonImg,
  IonSelect, 
  IonSelectOption,
  IonDatetime, 
  IonDatetimeButton,
  IonModal,
  IonTextarea,
  IonMenu,
  IonSpinner,
  IonChip, 
  IonCardSubtitle,
  IonNote,
  IonAccordionGroup,
  IonRadioGroup, 
  IonRadio,
  IonItemDivider,
  IonCheckbox
} from '@ionic/angular/standalone';
import { IonButton } from '@ionic/angular/standalone';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { NgbAlert, NgbAlertModule, NgbCarouselModule, NgbPaginationModule } from '@ng-bootstrap/ng-bootstrap';
import { ModalController } from '@ionic/angular';
import { CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';


@NgModule({
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  declarations: [],
  providers: [ModalController],
  imports: [
    IonCheckbox,
    IonContent,
    IonHeader,
    IonTitle,
    IonToolbar,
    CommonModule,
    FormsModule,
    IonCard,
    IonCardContent,
    IonCardHeader,
    IonCardTitle,
    IonSearchbar,
    IonButton,
    IonButtons,
    IonAvatar,
    IonThumbnail,
    IonTabs,
    IonTabBar,
    IonTabButton,
    IonIcon,
    IonLabel,
    IonItem,
    IonList,
    IonPopover,
    MatMenuModule, 
    MatMenuTrigger,
    IonInput,
    ReactiveFormsModule,
    IonText,
    IonBackButton,
    IonCol,
    IonRow,
    IonBadge,
    IonGrid,
    IonFooter,
    IonSegment, 
    IonSegmentButton,
    IonImg,
    IonSelect, 
    IonSelectOption,
    IonDatetime, 
    IonDatetimeButton,
    IonModal,
    IonTextarea,
    IonMenu,
    NgbPaginationModule,
    NgbAlertModule,
    NgbAlert,
    NgbCarouselModule,
    IonSpinner,
    IonChip, 
    IonCardSubtitle,
    IonNote,
    IonAccordionGroup,
    IonRadioGroup, 
    IonRadio, 
    IonItemDivider,
    IonicModule
  ],
  exports: [
    IonCheckbox,
    IonContent,
    IonHeader,
    IonTitle,
    IonToolbar,
    CommonModule,
    FormsModule,
    IonCard,
    IonCardContent,
    IonCardHeader,
    IonCardTitle,
    IonSearchbar,
    IonButton,
    IonButtons,
    IonAvatar,
    IonThumbnail,
    IonTabs,
    IonTabBar,
    IonTabButton,
    IonIcon,
    IonLabel,
    IonItem,
    IonList,
    IonPopover,
    MatMenuModule, 
    MatMenuTrigger,
    IonInput,
    ReactiveFormsModule,
    IonText ,
    IonBackButton,
    IonCol,
    IonRow,
    IonBadge,
    IonGrid,
    IonFooter,
    IonSegment, 
    IonSegmentButton,
    IonImg,
    IonSelect, 
    IonSelectOption,
    IonDatetime, 
    IonDatetimeButton,
    IonModal,
    IonTextarea,
    IonMenu,
    NgbPaginationModule, 
    NgbAlertModule,
    NgbAlert,
    NgbCarouselModule,
    IonSpinner,
    IonChip, 
    IonCardSubtitle,
    IonNote,
    IonAccordionGroup,
    IonRadioGroup, 
    IonRadio, 
    IonItemDivider,
  ]
})
export class SharedModule { }


/* import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { IonicModule } from '@ionic/angular';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { MatMenuModule } from '@angular/material/menu';
import { NgbAlertModule, NgbCarouselModule, NgbPaginationModule } from '@ng-bootstrap/ng-bootstrap';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    IonicModule,
    MatMenuModule,
    NgbPaginationModule,
    NgbAlertModule,
    NgbCarouselModule
  ],
  exports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    IonicModule,
    MatMenuModule,
    NgbPaginationModule,
    NgbAlertModule,
    NgbCarouselModule
  ]
})
export class SharedModule {} */
