import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {MatMenuModule, MatMenuTrigger} from '@angular/material/menu';

import {
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonButtons,
  IonCardTitle,
  IonSearchbar,
  IonContent,
  IonHeader,
  IonTitle,
  IonAvatar,
  IonThumbnail,
  IonTabs,
  IonTabBar,
  IonTabButton,
  IonIcon,
  IonLabel,
  IonItem,
  IonList,
  IonPopover,
  IonToolbar,
  IonInput,
  IonText,
  IonBackButton,
  IonCol,
  IonRow,
  IonBadge,
  IonGrid,
  IonFooter,
  IonSegment, 
  IonSegmentButton,
  IonImg,
  IonSelect, 
  IonSelectOption,
  IonDatetime, 
  IonDatetimeButton,
  IonModal,
  IonTextarea,
  IonMenu
} from '@ionic/angular/standalone';
import { IonButton } from '@ionic/angular/standalone';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { NgbPaginationModule, NgbAlertModule, NgbCarouselModule } from '@ng-bootstrap/ng-bootstrap';
import { NgbAlert } from '@ng-bootstrap/ng-bootstrap';
@NgModule({
  declarations: [],
  providers:[],
  imports: [
    IonContent,
    IonHeader,
    IonTitle,
    IonToolbar,
    CommonModule,
    FormsModule,
    IonCard,
    IonCardContent,
    IonCardHeader,
    IonCardTitle,
    IonSearchbar,
    IonButton,
    IonButtons,
    IonAvatar,
    IonThumbnail,
    IonTabs,
    IonTabBar,
    IonTabButton,
    IonIcon,
    IonLabel,
    IonItem,
    IonList,
    IonPopover,
    MatMenuModule, 
    MatMenuTrigger,
    IonInput,
    ReactiveFormsModule,
    IonText,
    IonBackButton,
    IonCol,
    IonRow,
    IonBadge,
    IonGrid,
    IonFooter,
    IonSegment, 
    IonSegmentButton,
    IonImg,
    IonSelect, 
    IonSelectOption,
    IonDatetime, 
    IonDatetimeButton,
    IonModal,
    IonTextarea,
    IonMenu,
    NgbPaginationModule,
    NgbAlertModule,
    NgbAlert,
    NgbCarouselModule
  ],
  exports: [
    IonContent,
    IonHeader,
    IonTitle,
    IonToolbar,
    CommonModule,
    FormsModule,
    IonCard,
    IonCardContent,
    IonCardHeader,
    IonCardTitle,
    IonSearchbar,
    IonButton,
    IonButtons,
    IonAvatar,
    IonThumbnail,
    IonTabs,
    IonTabBar,
    IonTabButton,
    IonIcon,
    IonLabel,
    IonItem,
    IonList,
    IonPopover,
    MatMenuModule, 
    MatMenuTrigger,
    IonInput,
    ReactiveFormsModule,
    IonText ,
    IonBackButton,
    IonCol,
    IonRow,
    IonBadge,
    IonGrid,
    IonFooter,
    IonSegment, 
    IonSegmentButton,
    IonImg,
    IonSelect, 
    IonSelectOption,
    IonDatetime, 
    IonDatetimeButton,
    IonModal,
    IonTextarea,
    IonMenu,
    NgbPaginationModule, 
    NgbAlertModule,
    NgbAlert,
    NgbCarouselModule
  ]
})
export class SharedModule { }
